# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.ImageField(default=False, upload_to='events_folder/'),
        ),
    ]
